### ISSUE TITLE
UI/UX improvements

### ISSUE THREAD

**Issue by jmatsushita** [iilab/openmentoring-mobile#85]
- [x] Make Topic name in Bold in Index page.
- [x] Make redundant close button (X) into a question mark leading to an info page (displaying metadata) #78 
- [x] Allow clicking on the title (not the arrow) to expand topics #81 
- [x] Orient user when moving between Topics #79
- [x] Close button in the settings window is too faint. How about a bold cross (x) instead! #63
- [x] Subtopic Content download icon alignment #62
- [ ] Glossary link (with "Add lesson to reading list" checkmark)

**Comment by jmatsushita** [comment]
https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/

**Comment by jmatsushita** [comment]
Closing and creating a glossary related issue.
